openapi: 3.0.1
info:
  title: IoT Sensor Data API
  version: '1.0'
paths:
  /sensor-data:
    post:
      summary: Receive sensor data
      operationId: sendSensorData
      requestBody:
        description: Sensor data payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SensorData'
      responses:
        '200':
          description: Data received successfully
components:
  schemas:
    SensorData:
      type: object
      properties:
        device_id:
          type: string
        timestamp:
          type: string
          format: date-time
        temperature:
          type: number
        humidity:
          type: number
        air_quality_index:
          type: number
        light_intensity:
          type: number
        sound_level:
          type: number
        pressure:
          type: number
        co2_level:
          type: number
        uv_index:
          type: number
        wind_speed:
          type: number
        wind_direction:
          type: string
        battery_level:
          type: number
        signal_strength:
          type: number
        latitude:
          type: number
        longitude:
          type: number
        orientation:
          type: string
        motion_detected:
          type: boolean
      required:
        - device_id
        - timestamp
        - temperature
        - humidity
        # Add required fields if necessary
      # ... existing code ...